apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-hello-kubernetes
  namespace: argocd
spec:
  destination:
    namespace: nodejs
    server: 'https://kubernetes.default.svc'
  source:
    path: dc2/
    repoURL: 'https://github.com/s-u-b-h-a-k-a-r-cicd/hello-kubernetes-prod-config'
    targetRevision: HEAD
  syncPolicy:
   automated:
     selfHeal: true
     prune: true
  project: default