apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prereq-nodejs-production
  namespace: argocd
spec:
  destination:
    namespace: nsnodejs
    server: 'https://kubernetes.default.svc'
  source:
    path: app-prerequisites/overlays/dc2/production/applications
    repoURL: 'https://github.com/s-u-b-h-a-k-a-r-cicd/k8s-argocd-apps'
    targetRevision: HEAD
  syncPolicy:
   automated:
     selfHeal: true
     prune: true
  project: default