apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ss-prereq-opstools-production
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: app-prerequisites/overlays/dc2/production/opstools
    repoURL: 'https://github.com/alaghusundhar/k8s-argocd-apps'
    targetRevision: HEAD
  syncPolicy:
   automated:
     selfHeal: true
     prune: true
  project: default